version: '3.8'
services: 
  app:
    image: revproxy:latest
    container_name: revproxy
    build: 
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - 8080:8080
      - 9001:9001
    environment:
      - REVPROXY_PROPERTIES=file:///home/gradle/revproxy/conf/application.properties
